name: Build Redmi 9 NetHunter (A13)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Neternels/android_kernel_xiaomi_mt6768
          kernel-branch: eleven
          config: lancelot_defconfig
          arch: arm64
          android-version: 13
          
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          aosp-gcc: true
          
          nethunter: true
          ksu: true
