name: Find Config Name
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make bc bison flex build-essential libssl-dev libncurses5-dev
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Download Clang (Proton)
        run: |
          git clone --depth=1 -b master https://github.com/kdrag0n/proton-clang clang

      - name: Download Kernel
        run: |
          git clone --depth=1 -b genom-release https://github.com/Neternels/NetHunter-MT6768 kernel

      - name: Build Kernel
        run: |
          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
          cd kernel
          
          echo " "
          echo "=== СПИСОК ФАЙЛОВ В ПАПКЕ CONFIGS ==="
          ls -R arch/arm64/configs
          echo "====================================="
          echo " "
          
          make O=out ARCH=arm64 mt6768_defconfig
          
          scripts/config --file out/.config --enable CONFIG_USB_F_HID
          scripts/config --file out/.config --enable CONFIG_USB_CONFIGFS_F_HID
          
          make -j$(nproc) O=out \
                          ARCH=arm64 \
                          CC=clang \
                          CLANG_TRIPLE=aarch64-linux-gnu- \
                          CROSS_COMPILE=aarch64-linux-gnu- \
                          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                          HOSTCC=gcc \
                          HOSTCXX=g++
