name: Build Redmi 9 NetHunter Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Kernel Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Neternels/android_kernel_xiaomi_mt6768
          kernel-branch: eleven
          config: lancelot_defconfig
          arch: arm64
          
          aosp-clang: false
          
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          
          aosp-gcc: true
          
          ksu: true
          extra-make-args: |
            CONFIG_USB_F_HID=y
            CONFIG_USB_CONFIGFS_F_HID=y
            CONFIG_CFG80211=y
            CONFIG_MAC80211=y
            CONFIG_ATH9K_HTC=y
