name: Build Redmi 9 NetHunter (Fast Queue Fix)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Neternels/NetHunter-MT6768
          kernel-branch: genom-release
          config: lancelot_defconfig
          arch: arm64
          
          android-version: 11
          
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          aosp-gcc: true
          
          nethunter: true
          ksu: true
     
          extra-make-args: |
            HOSTCC=gcc
            HOSTCXX=g++
